## pulling the base image from building our continer

FROM python:3.13-slim

## copying uv for docker container vm setput from git uv reposetory

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

## mentioning the working directory inside the container

WORKDIR /code

ENV PATH="/code/.venv/bin:$PATH"

COPY  .python-version pyproject.toml uv.lock ./
RUN uv sync --locked

COPY  ingest_data.py /code/

## providing the commands for entry point

ENTRYPOINT ["python" , "ingest_data.py"]
